language: php

sudo: false

before_script:
    - composer self-update
    - composer update --no-interaction --prefer-source

script: vendor/bin/phpunit

matrix:
    include:
        - php: 7.0
        - php: 7.1
        - php: 7.2
    fast_finish: true